### ISSUE TITLE
Sonoff zigbee 3.0 dongle not starting...

### ISSUE THREAD

**Issue by geniesek** [zigbeenet/ZigbeeNet#171]
Hi, 
few months ago I ran the ZigBee2.0 controller using this great library, but now when I started using Sonoff zigbee 3.0 dongle, i am getting this in logs and dongle wont start the network. I expect this will be a simple, but I tried lot of steps with same effect. 

DBUG	[ZigBeeNet.Hardware.TI.CC2531.Implementation.CommandInterfaceImpl]	[0]	-->  SYS_RESET (Packet: subsystem=SYS, length=1, apiId=41 00, data=FE 01 41 00 01 41, checksum=41, error=False) 
WARN	[ZigBeeNet.Hardware.TI.CC2531.Network.NetworkManager]	[0]	Dongle reset failed. Assuming bootloader is running and sending magic byte 0xEF.
WARN	[ZigBeeNet.Hardware.TI.CC2531.Network.NetworkManager]	[0]	Attempt to get out from bootloader failed.
DBUG	[ZigBeeNet.Hardware.TI.CC2531.Network.NetworkManager]	[0]	Closing HARDWARE

Maybe this is not the exactly good place to ask, but I hope someone will help me. 

At least some forum would help.

**Comment by geniesek** [comment]
I had run the demo program with the dongle and got this log... could someone help me what i need to do to make the dongle run, please?

[21:42:33 DBG] Network state is updated to INITIALISING
[21:42:33 DBG] 00124B001CD4A39F: Data store: Node was restored.
[21:42:33 DBG] 00124B001CD4A39F: Updating Node 0
[21:42:33 DBG] 44523/1: Unsupported cluster 65535 - using ZclCustomCluster
[21:42:33 DBG] 44523/1: Unsupported cluster 65535 - using ZclCustomCluster
[21:42:33 DBG] 00158D00053F296D: Data store: Node was restored.
[21:42:33 DBG] 00158D00053F296D: Updating Node 44523
[21:42:33 DBG] CC2531 transport initialize
[21:42:33 DBG] Opening port COM17 at 115200 baud with FLOWCONTROL_OUT_NONE
[21:42:33 DBG] -->  SYS_RESET (Packet: subsystem=SYS, length=1, apiId=41 00, data=FE 01 41 00 01 41, checksum=41, error=False) 
[21:42:33 DBG] Discarded stream: expected start byte but received 0
[21:42:35 DBG] <-- Async incomming SYS_RESET_RESPONSE (FE 06 41 80 00 02 01 02 07 01 C0)
[21:42:35 DBG] Received Async Cmd: Packet: subsystem=SYS, length=6, apiId=41 80, data=FE 06 41 80 00 02 01 02 07 01 C0, checksum=C0, error=False
[21:42:35 DBG] -->  SYS_VERSION (Packet: subsystem=SYS, length=0, apiId=21 02, data=FE 00 21 02 23, checksum=23, error=False) 
[21:42:35 DBG] <-- Sync incomming SYS_VERSION_RESPONSE (FE 0A 61 02 02 01 02 07 01 3B 89 34 01 00 E9)
[21:42:35 INF] CC2531 version is Software=2.7 Product=1 Hardware=1 Transport=2
[21:42:35 DBG] -->  ZB_GET_DEVICE_INFO (Packet: subsystem=SAPI, length=1, apiId=26 06, data=FE 01 26 06 01 20, checksum=20, error=False) 
[21:42:35 ERR] Packet parsing failed due to exception: Index was outside the bounds of the array.
[21:42:35 DBG] Received a BAD PACKET Packet: subsystem=RES, length=0, apiId=00 00, data=FE 00 00 00 00, checksum=00, error=True, errorMessage=Index was outside the bounds of the array.
[21:42:35 DBG] Discarded stream: expected start byte but received 66
[21:42:36 DBG] ZB_GET_DEVICE_INFO executed and timed out while waiting for response.
[21:42:36 WRN] Failed GetDeviceInfo for IEEE_ADDR due to null value
[21:42:36 DBG] FFFFFFFFFFFFFFFF: Adding local node to network, NWK=0
[21:42:36 DBG] FFFFFFFFFFFFFFFF: Updating Node 0
[21:42:36 DBG] Adding supported client cluster 6
[21:42:36 DBG] ClusterMatcher starting
[21:42:36 DBG] ClusterMatcher adding client cluster 6
[21:42:36 DBG] Adding supported client cluster 768
[21:42:36 DBG] ClusterMatcher adding client cluster 768
[21:42:36 DBG] Adding supported client cluster 1280
[21:42:36 DBG] ClusterMatcher adding client cluster 1280
[21:42:36 DBG] -->  UTIL_LED_CONTROL (Packet: subsystem=UTIL, length=2, apiId=27 0A, data=FE 02 27 0A 01 00 2E, checksum=2E, error=False) 
[21:42:36 DBG] <-- Sync incomming UTIL_LED_CONTROL_RESPONSE (FE 01 67 0A 00 6C)
[21:42:36 DBG] -->  UTIL_LED_CONTROL (Packet: subsystem=UTIL, length=2, apiId=27 0A, data=FE 02 27 0A 02 00 2D, checksum=2D, error=False) 
[21:42:36 DBG] <-- Sync incomming UTIL_LED_CONTROL_RESPONSE (FE 01 67 0A 00 6C)
[21:42:36 DBG] -->  ZB_GET_DEVICE_INFO (Packet: subsystem=SAPI, length=1, apiId=26 06, data=FE 01 26 06 06 27, checksum=27, error=False) 
[21:42:36 ERR] Packet parsing failed due to exception: Index was outside the bounds of the array.
[21:42:36 DBG] Received a BAD PACKET Packet: subsystem=RES, length=0, apiId=00 00, data=FE 00 00 00 00, checksum=00, error=True, errorMessage=Index was outside the bounds of the array.
[21:42:36 DBG] Discarded stream: expected start byte but received 66
[21:42:37 DBG] ZB_GET_DEVICE_INFO executed and timed out while waiting for response.
[21:42:37 WRN] Failed GetDeviceInfo for PAN_ID due to null value
PAN ID           = 65535
[21:42:37 DBG] -->  ZB_GET_DEVICE_INFO (Packet: subsystem=SAPI, length=1, apiId=26 06, data=FE 01 26 06 07 26, checksum=26, error=False) 
[21:42:37 ERR] Packet parsing failed due to exception: Index was outside the bounds of the array.
[21:42:37 DBG] Received a BAD PACKET Packet: subsystem=RES, length=0, apiId=00 00, data=FE 00 00 00 00, checksum=00, error=True, errorMessage=Index was outside the bounds of the array.
[21:42:37 DBG] Discarded stream: expected start byte but received 66
[21:42:38 DBG] ZB_GET_DEVICE_INFO executed and timed out while waiting for response.
[21:42:38 WRN] Failed GetDeviceInfo for EXT_PAN_ID due to null value
Extended PAN ID  = 0000000000000000
[21:42:38 DBG] -->  ZB_GET_DEVICE_INFO (Packet: subsystem=SAPI, length=1, apiId=26 06, data=FE 01 26 06 05 24, checksum=24, error=False) 
[21:42:38 ERR] Packet parsing failed due to exception: Index was outside the bounds of the array.
[21:42:38 DBG] Received a BAD PACKET Packet: subsystem=RES, length=0, apiId=00 00, data=FE 00 00 00 00, checksum=00, error=True, errorMessage=Index was outside the bounds of the array.
[21:42:38 DBG] Discarded stream: expected start byte but received 66
[21:42:39 DBG] ZB_GET_DEVICE_INFO executed and timed out while waiting for response.
[21:42:39 WRN] Failed GetDeviceInfo for CHANNEL due to null value
Channel          = 255
[21:42:39 DBG] -->  ZB_READ_CONFIGURATION (Packet: subsystem=SAPI, length=1, apiId=26 04, data=FE 01 26 04 62 41, checksum=41, error=False) 
[21:42:39 ERR] Packet parsing failed due to exception: Index was outside the bounds of the array.
[21:42:39 DBG] Received a BAD PACKET Packet: subsystem=RES, length=0, apiId=00 00, data=FE 00 00 00 00, checksum=00, error=True, errorMessage=Index was outside the bounds of the array.
[21:42:39 DBG] Discarded stream: expected start byte but received 64
[21:42:40 DBG] ZB_READ_CONFIGURATION executed and timed out while waiting for response.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ZigBeeNet.Hardware.TI.CC2531.Network.NetworkManager.GetZigBeeNetworkKey() in D:\Projects\RPi\ZigBee\libraries\ZigBeeNet.Hardware.TI.CC2531\Network\NetworkManager.cs:line 1282
   at ZigBeeNet.Hardware.TI.CC2531.ZigBeeDongleTiCc2531.get_ZigBeeNetworkKey() in D:\Projects\RPi\ZigBee\libraries\ZigBeeNet.Hardware.TI.CC2531\ZigBeeDongleTiCc2531.cs:line 67
   at ZigBeeNet.ZigBeeNetworkManager.get_ZigBeeNetworkKey() in D:\Projects\RPi\ZigBee\libraries\ZigBeeNet\ZigBeeNetworkManager.cs:line 437
   at ZigBeeNet.PlayGround.Program.Main(String[] args) in D:\Projects\RPi\ZigBee\samples\ZigBeeNet.PlayGround\Program.cs:line 240

**Comment by geniesek** [comment]
No response, thx
